### ISSUE TITLE
쿠키관련 문제입니다.

### ISSUE THREAD

**Issue by lifeisegg123** [pyo940216/musicalpage_server#11]
![image](https://user-images.githubusercontent.com/58962402/102018144-b37f4b80-3dae-11eb-973d-6886c3cb6a5f.png)
위와같은 문제가 발생하며 쿠키가 브라우저에 저장이 되지 않습니다. sameSite관련 설정이 필요한 것으로 보이는데 확인부탁드립니다.

**Comment by m-pyo** [comment]
sameSite 설정을 lax 로 설정하여 쿠키를 설정하도록 수정.
수정후 정상동작하는것을 확인하였기에 해당 이슈를 크로즈합니다.
