### ISSUE TITLE
pageList 함수 내부 오타

### ISSUE THREAD

**Issue by lifeisegg123** [pyo940216/musicalpage_server#4]
case "prev":
      **topage** = nowPage - 1;
      break;
case "next":
      **topage** = nowPage + 1;
      break;
case "end":
      const fullDataCount = await MusicalInfo.find().countDocuments();
      **topage** = Math.ceil(fullDataCount / limitCount);
      break;

topage=>toPage로 변경 요청 드립니다.

**Comment by m-pyo** [comment]
topage=>toPage 변경
