### ISSUE TITLE
수정기능 이미지 등록문제

### ISSUE THREAD

**Issue by lifeisegg123** [pyo940216/musicalpage_server#9]
수정기능에 이미지 변경이 없을시 이미지 데이터전송을 안하게 두었는데, 저장된 이미지가 사라지는 현상이 발생합니다. 확인 부탁드립니다.

**Comment by m-pyo** [comment]
base64 문자열 변환기능 현재 미탑재로 현재 업로드 자체가 불가능한 상태
차후 대응예정이므로 완료 처리
